### ISSUE TITLE
Error messages not appearing in console

### ISSUE THREAD

**Issue by CatherineH** [mfitzp/Wooey#10]
When running my script, it reports an error in the status, but nothing is written to the console. In addition, the daemon reports:

```
cholloway@nb-cholloway:~/Wooey$ python manage.py start_daemon
INFO:root:Starting job 1.
ERROR:root:
```

This script works fine when run from the command line. 

Even this minimal script produces the error:

```
#!/usr/bin/env python

import utils
import argparse

parser = argparse.ArgumentParser(description="Plot Velocity Controller error histograms")
parser.add_argument("-f", "--filename", dest="filename", default='../data/velocity_tester/pelican/z position/z_1.0_limit_2015-05-29-10-17-14.bag',
                  help="name of the file to plot graph for")
parser.add_argument("-c", "--component", dest="component", default='z', help="Component to analyze")
parser.add_argument("-n","--uav_number", dest="uav_number", default=5, help="UAV number to analyze")

args = parser.parse_args()

print "Got "+args.filename+" with component: "+args.component+" uav number: "+str(args.uav_number)
```

**Comment by streetmapp** [comment]
I ran into a similar issue (https://github.com/mfitzp/Wooey/issues/7), when I was getting setup. The issue was I actually didn't have my own script set to be executable. Same sort of symptom, could run script fine on the command line, but failed through Wooey with same message.

**Comment by CatherineH** [comment]
yep, that was it. This should maybe be in the documentation?
