### ISSUE TITLE
Username and password form layout [minor]

### ISSUE THREAD

**Issue by yoavram** [mfitzp/Wooey#5]
This is a very minor issue as it only concerns aestheticsand not function. Feel free to "wontfix" :)
The username and the password inputs are not above each other, making a strange layout.

![image](https://cloud.githubusercontent.com/assets/1288133/6958724/9d6bb686-d918-11e4-98a5-9fa823646b46.png)

**Comment by mfitzp** [comment]
This is definitely a will-fix, it's ugly. I have some bigger work to do around the menu for smaller screens so will be looking at it soon.

**Comment by mfitzp** [comment]
This should be fixed in current `master`. The mobile tweaks are a bit more complex so will come later.
